name: 'Build and push Docker images'

runs:
  using: "composite"

  steps:
    - name: ğŸ› ï¸ Build and push ğŸ³ Docker images
      uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
