name: 'Build and push Docker images'

runs:
  using: "composite"

  steps:
    - name: ğŸ› ï¸ Build and push ğŸ³ Docker images
      uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6.13.0
