name: 'Build and push Docker images'

runs:
  using: "composite"

  steps:
    - name: ğŸ› ï¸ Build and push ğŸ³ Docker images
      uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc # v6.11.0
